<?php

namespace DoctrineProxies\__CG__\Jet\Domain\PLD\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StockInquiry extends \Jet\Domain\PLD\Entity\StockInquiry implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'moduleCode', '' . "\0" . 'Jet\\Domain\\PLD\\Entity\\StockInquiry' . "\0" . 'purpose', '' . "\0" . 'Jet\\Domain\\PLD\\Entity\\StockInquiry' . "\0" . 'details', 'createdAt', 'updatedAt', 'documentNumber', 'trackingNumber', 'createdByUsername', '' . "\0" . 'Jet\\Domain\\PLD\\Entity\\StockInquiry' . "\0" . 'createdBy'];
        }

        return ['__isInitialized__', 'moduleCode', '' . "\0" . 'Jet\\Domain\\PLD\\Entity\\StockInquiry' . "\0" . 'purpose', '' . "\0" . 'Jet\\Domain\\PLD\\Entity\\StockInquiry' . "\0" . 'details', 'createdAt', 'updatedAt', 'documentNumber', 'trackingNumber', 'createdByUsername', '' . "\0" . 'Jet\\Domain\\PLD\\Entity\\StockInquiry' . "\0" . 'createdBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StockInquiry $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPurpose(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurpose', []);

        return parent::getPurpose();
    }

    /**
     * {@inheritDoc}
     */
    public function getDetails(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetails', []);

        return parent::getDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetail(\Jet\Domain\PLD\Entity\StockInquiryDetail $stockInquiryDetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetail', [$stockInquiryDetail]);

        return parent::addDetail($stockInquiryDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentNumber', []);

        return parent::getDocumentNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function reserveDocumentNumber(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'reserveDocumentNumber', []);

        parent::reserveDocumentNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function refreshDocumentNumber(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'refreshDocumentNumber', []);

        parent::refreshDocumentNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function commitAndPersist(\Doctrine\ORM\EntityManagerInterface $em): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'commitAndPersist', [$em]);

        return parent::commitAndPersist($em);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackingNumber(): \Jet\Domain\System\Entity\TrackingNumber
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackingNumber', []);

        return parent::getTrackingNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy(): \Jet\Domain\System\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

}
